@startuml
actor App
participant GAM
participant SCORE
database Database

App -> Database : Modelos disponíveis
activate Database
App <- Database
App -> Database : Dados disponíveis
App <- Database
deactivate Database

App -> GAM : Treino do modelo
activate GAM
App <- GAM
deactivate GAM

App -> SCORE : Avalia o modelo
activate SCORE
App <- SCORE
deactivate SCORE 

@enduml