@startuml
actor App
participant MODELS
participant SCORE
database Database

App -> Database : Modelos disponíveis
activate Database
App <- Database
App -> Database : Dados disponíveis
App <- Database
deactivate Database

App -> MODELS : Treino do modelo
activate MODELS
App <- MODELS
deactivate MODELS

App -> SCORE : Avalia o modelo
activate SCORE
App <- SCORE
deactivate SCORE 

@enduml